services:
  osrm-backend:
    image: osrm/osrm-backend:latest
    container_name: kerno-osrm-backend
    ports:
      - "5003:5000"
    volumes:
      - ./data:/data
    entrypoint: /bin/bash
    command: >
      -c "
      if [ ! -f /data/bolivia-latest.osrm ]; then
        echo 'Procesando datos de Bolivia...';
        osrm-extract -p /opt/car.lua /data/bolivia-latest.osm.pbf &&
        osrm-partition /data/bolivia-latest.osrm &&
        osrm-customize /data/bolivia-latest.osrm &&
        echo 'Procesamiento completado.';
      fi;
      echo 'Iniciando servidor OSRM en puerto 5000...';
      osrm-routed --algorithm mld /data/bolivia-latest.osrm --max-table-size 8000
      "
    restart: unless-stopped
